server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MemoraDB
      database: MemoraDB
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: C:\Users\hp\Desktop\test
      

  mail:
    host: smtp.gmail.com
    port: 465
    username: s12027995@stu.najah.edu
    password: "lpwu dkgw oxrm yzdr"
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.timeout: 2500

logging:
  level:
    com:
      springsecurity:
        demo: DEBUG
    org:
      hibernate: WARN
      springframework: WARN

upload:
  dir : /home/qdl/Desktop/gallery/

img:
  imgURL: http://xxx:8080/images/


Chatbot:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
    key: AIzaSyAM1KzNd_sph56IhhNalHPQgeVC6JqU_5s

