server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MemoraDB
      database: MemoraDB
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  
  mail:
    host: smtp.gmail.com
    port: 465
    username: s12027995@stu.najah.edu
    password: "lpwu dkgw oxrm yzdr"
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.timeout: 2500
# 日志信息
logging:
  level:
    com:
      springsecurity:
        demo: DEBUG
    org:
      hibernate: WARN
      springframework: WARN

# 上传路径
upload:
  dir : /home/qdl/Desktop/gallery/

# 图片网络访问路径
img:
  imgURL: http://xxx:8080/images/